notifications:
  email: false
  slack:
    secure: dOdL/KDP86cm4ypZrxF9a4/ysajPh5bphQv7rliQ0LCYGn+Fu5kescZKKYW8iZsfk8S0XiPW5jeZxf7aYLGJHwRYXUOImFNCeA9H/I/S1IaK+MT+WxU4AL4zp+YfXiGy+c4mWIcpJCp2h1fZ+H48rQC1YaNIUVfG2oR3qK+AAZpsWNfSN3WNQjXH4XlfYfHs1aNGnmAFDJLnZGCRCgKGxBkFRf+MBV70ZLqywJfhaxip4r9pvz4nXFzNwVrPHytZPtYZDwcIJlC4fTVNFPxwf6h1ppKbJwtPIWfcbq7vwKmiSvDYZ8NU6RKdgPFSHoWTlwTHDsQ50ZHDsfQCg0I/SNxZO070Vk1Jch1tRTyQidB08qtRyQ4fKbYtwx+G2jhWzV+yF2AqXv6NVg4oiiwm9ZrE5RG4fHucL0UkYuj+pStArH/kn/8VRnmxqrHAkkc8piB9PXPKygiTKxhmY+Lcei1Gx4tYXIc1hofEKs0gtFKDaSzDUUTfuRg7pssKBZpbE/woX+kCmPEHCxWvCphaV8OEl7woCXH0mRG3zDGo6ItkZ0PJ1e33gFX8ouVPcGigJ2kNE35uIthcCflXyfThkxaxzEKiaeV1bnLV7qV7/rRI/atwk6MITiHIBuEDb9/VA9eZDSNfGbGM+iW/84uhDr4dNfgvyQpPbD0k2GBov2o=
sudo: false
language: java
before_install: 
after_success:
- mvn clean cobertura:cobertura coveralls:report
